// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm4Nuz8dnDtvPd9cLDFUUf_mbhKdUTj5Y',
    appId: '1:675467833617:web:00446f70740eeb884d9cb0',
    messagingSenderId: '675467833617',
    projectId: 'twnsqr-townsquare',
    authDomain: 'twnsqr-townsquare.firebaseapp.com',
    storageBucket: 'twnsqr-townsquare.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQxuc8PiGdc0_aavWPEWscIYGxJU7Lqw4',
    appId: '1:675467833617:android:819e3596e4df9ce54d9cb0',
    messagingSenderId: '675467833617',
    projectId: 'twnsqr-townsquare',
    storageBucket: 'twnsqr-townsquare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDztn5Hyxy9nCS1legh20JH69sN4F6p-QY',
    appId: '1:675467833617:ios:2eec6423be84f4554d9cb0',
    messagingSenderId: '675467833617',
    projectId: 'twnsqr-townsquare',
    storageBucket: 'twnsqr-townsquare.firebasestorage.app',
    iosBundleId: 'com.example.townsquare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDztn5Hyxy9nCS1legh20JH69sN4F6p-QY',
    appId: '1:675467833617:ios:2eec6423be84f4554d9cb0',
    messagingSenderId: '675467833617',
    projectId: 'twnsqr-townsquare',
    storageBucket: 'twnsqr-townsquare.firebasestorage.app',
    iosBundleId: 'com.example.townsquare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm4Nuz8dnDtvPd9cLDFUUf_mbhKdUTj5Y',
    appId: '1:675467833617:web:0f1c9078085320b84d9cb0',
    messagingSenderId: '675467833617',
    projectId: 'twnsqr-townsquare',
    authDomain: 'twnsqr-townsquare.firebaseapp.com',
    storageBucket: 'twnsqr-townsquare.firebasestorage.app',
  );
}
